// src/components/Navbar.jsx
import { useState } from "react";
import { CgMenuRightAlt } from "react-icons/cg";
import { SocialMediaIcons } from "./SocialMediaIcons";

export const Navbar = () => {
  const [openOptions, setOpenOptions] = useState(false);

  const handleOpenOptions = () => {
    setOpenOptions(!openOptions);
  };

  const handleCloseOptions = () => {
    setOpenOptions(false);
  };

  return (
    <header className="w-full bg-white border-b border-gray-200 sticky top-0 z-[9999]">
      <nav className="flex justify-between items-center p-4 container mx-auto">
        <div className="flex gap-2 items-center cursor-pointer">
          <img className="size-16" src="/logo.png" alt="Logo" />
          <h2 className="text-xl font-semibold text-black">M-S</h2>
        </div>

        <div>
          <CgMenuRightAlt
            size={30}
            className="cursor-pointer text-gray-500 hover:text-blue-500 md1:hidden"
            onClick={handleOpenOptions}
          />

          <ul
            className={`absolute top-[4.6rem] right-0 w-full bg-white border border-gray-200 rounded-lg shadow-md mt-2 p-4 grid transform -translate-x-full duration-200 ${
              openOptions ? "translate-x-0" : ""
            } md1:relative md1:shadow-none md1:bg-transparent md1:border-none md1:p-0 md1:flex md1:translate-x-0 md1:top-0 md1:m-0 md1:gap-4
              `}
          >
            <a href="#aboutme" onClick={handleCloseOptions}>
              <li className="text-gray-500 text-base border-b px-2 py-4 rounded-b hover:bg-gray-100 duration-300 cursor-pointer md1:text-black md1:font-semibold md1:py-0 md1:border-none md1:hover:text-blue-500 md1:hover:bg-transparent">
                Sobre mi
              </li>
            </a>
            <a href="#skills" onClick={handleCloseOptions}>
              <li className="text-gray-500 text-base border-b px-2 py-4 rounded-b hover:bg-gray-100 duration-300 cursor-pointer md1:text-black md1:font-semibold md1:py-0 md1:border-none md1:hover:text-blue-500 md1:hover:bg-transparent">
                Servicios
              </li>
            </a>
            <a href="#projects" onClick={handleCloseOptions}>
              <li className="text-gray-500 text-base border-b px-2 py-4 rounded-b hover:bg-gray-100 duration-300 cursor-pointer md1:text-black md1:font-semibold md1:py-0 md1:border-none md1:hover:text-blue-500 md1:hover:bg-transparent">
                Proyectos
              </li>
            </a>
            <a href="#contact" onClick={handleCloseOptions}>
              <li className="text-gray-500 text-base border-b px-2 py-4 rounded-b hover:bg-gray-100 duration-300 cursor-pointer md1:text-black md1:font-semibold md1:py-0 md1:border-none md1:hover:text-blue-500 md1:hover:bg-transparent">
                Contacto
              </li>
            </a>
            <li className="text-base px-2 py-4 rounded-b mt-4 md1:hidden">
              <SocialMediaIcons />
            </li>
          </ul>
        </div>
      </nav>
    </header>
  );
};

// src/components/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";

const isMenuOpen = ref(false);
const activeSection = ref("homePage");

const sections = [
  { id: "homePage", label: "Inicio", icon: "/icons/home.svg" },
  { id: "aboutmePage", label: "Sobre mí", icon: "/icons/user.svg" },
  { id: "worksPage", label: "Proyectos", icon: "/icons/works.svg" },
  { id: "skillsPage", label: "Habilidades", icon: "/icons/skills.svg" },
  { id: "contactPage", label: "Contacto", icon: "/icons/contact.svg" },
];

const closeMenu = () => {
  isMenuOpen.value = false;
};

const scrollToSection = (id: string) => {
  const el = document.getElementById(id);
  if (el) {
    el.scrollIntoView({ behavior: "smooth" });
    closeMenu();
  }
};

const handleScroll = () => {
  const scrollPosition = window.scrollY + 150;

  for (const section of sections) {
    const el = document.getElementById(section.id);
    if (el) {
      const { offsetTop, offsetHeight } = el;
      if (
        scrollPosition >= offsetTop &&
        scrollPosition < offsetTop + offsetHeight
      ) {
        activeSection.value = section.id;
        break;
      }
    }
  }
};

onMounted(() => {
  window.addEventListener("scroll", handleScroll);
});

onUnmounted(() => {
  window.removeEventListener("scroll", handleScroll);
});
</script>

<template>
  <div
    class="fixed inset-0 bg-black/30 z-40 transition-opacity duration-300 md:hidden"
    :class="{
      'opacity-100 pointer-events-auto': isMenuOpen,
      'opacity-0 pointer-events-none': !isMenuOpen,
    }"
    @click="closeMenu"
  />

  <header
    class="w-full border-b border-gray-200 fixed top-0 bg-white/80 backdrop-blur-md z-50 animate__animated animate__fadeInDown"
  >
    <div class="container mx-auto flex items-center justify-between p-4">
      <h2 class="text-2xl font-normal text-gray-900">Martin Simarra</h2>

      <nav class="relative z-50">
        <img
          class="size-7 md:hidden cursor-pointer"
          :src="isMenuOpen ? '/icons/close.svg' : '/icons/menuHamburguer.svg'"
          :alt="isMenuOpen ? 'Cerrar menú' : 'Abrir menú'"
          @click="isMenuOpen = !isMenuOpen"
        />

        <ul
          class="absolute -right-3.5 top-9 mt-2 w-97.5 py-2 bg-white border border-gray-200 rounded shadow-lg transition-all duration-300 ease-in-out transform origin-top md:hidden"
          :class="{
            'opacity-100 scale-100 pointer-events-auto': isMenuOpen,
            'opacity-0 scale-95 pointer-events-none': !isMenuOpen,
          }"
        >
          <li
            v-for="section in sections"
            :key="section.id"
            class="flex items-center gap-2 p-4 border-b border-gray-200 rounded-xl text-sm hover:bg-gray-100 cursor-pointer transition"
            :class="{
              'text-black font-semibold': activeSection === section.id,
            }"
            @click="scrollToSection(section.id)"
          >
            <img class="size-5" :src="section.icon" :alt="section.label" />
            {{ section.label }}
          </li>
        </ul>

        <ul class="hidden md:flex gap-6 text-sm text-gray-600 font-normal">
          <li
            v-for="section in sections"
            :key="section.id"
            class="text-base cursor-pointer hover:text-black hover:scale-105 transition"
            :class="{
              'border-b-2 border-black font-semibold text-black':
                activeSection === section.id,
            }"
            @click="scrollToSection(section.id)"
          >
            {{ section.label }}
          </li>
        </ul>
      </nav>
    </div>
  </header>
</template>
